/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    jobs: Job;
    products: Product;
    'contact-submissions': ContactSubmission;
    'job-applications': JobApplication;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    navbar: Navbar;
    'hero-logos': HeroLogo;
    'home-hero': HomeHero;
    'stats-bar': StatsBar;
    expertise: Expertise;
    'about-section': AboutSection;
    footer: Footer;
    technologies: Technology;
    'about-us-page': AboutUsPage;
    'contact-page': ContactPage;
    'products-page': ProductsPage;
    'careers-page': CareersPage;
    'culture-page': CulturePage;
  };
  globalsSelect: {
    navbar: NavbarSelect<false> | NavbarSelect<true>;
    'hero-logos': HeroLogosSelect<false> | HeroLogosSelect<true>;
    'home-hero': HomeHeroSelect<false> | HomeHeroSelect<true>;
    'stats-bar': StatsBarSelect<false> | StatsBarSelect<true>;
    expertise: ExpertiseSelect<false> | ExpertiseSelect<true>;
    'about-section': AboutSectionSelect<false> | AboutSectionSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    technologies: TechnologiesSelect<false> | TechnologiesSelect<true>;
    'about-us-page': AboutUsPageSelect<false> | AboutUsPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'products-page': ProductsPageSelect<false> | ProductsPageSelect<true>;
    'careers-page': CareersPageSelect<false> | CareersPageSelect<true>;
    'culture-page': CulturePageSelect<false> | CulturePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: string;
  title: string;
  dept: string;
  location: string;
  type: string;
  desc: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  /**
   * URL of the product image
   */
  imageUrl?: string | null;
  slug: string;
  name: string;
  tagline: string;
  shortDescription: string;
  fullDescription: string;
  category: string;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  idealFor?:
    | {
        audience?: string | null;
        id?: string | null;
      }[]
    | null;
  paymentOptions?:
    | {
        title: string;
        monthlyPrice?: string | null;
        yearlyPrice?: string | null;
        monthlyFeatures?:
          | {
              feature?: string | null;
              id?: string | null;
            }[]
          | null;
        yearlyFeatures?:
          | {
              feature?: string | null;
              id?: string | null;
            }[]
          | null;
        features?:
          | {
              feature?: string | null;
              id?: string | null;
            }[]
          | null;
        yearlyBonus?: string | null;
        isCustomise?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  subject: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: string;
  fullName: string;
  email: string;
  phone: string;
  jobTitle: string;
  resume: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'jobs';
        value: string | Job;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: string | JobApplication;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  dept?: T;
  location?: T;
  type?: T;
  desc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  imageUrl?: T;
  slug?: T;
  name?: T;
  tagline?: T;
  shortDescription?: T;
  fullDescription?: T;
  category?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  idealFor?:
    | T
    | {
        audience?: T;
        id?: T;
      };
  paymentOptions?:
    | T
    | {
        title?: T;
        monthlyPrice?: T;
        yearlyPrice?: T;
        monthlyFeatures?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        yearlyFeatures?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        yearlyBonus?: T;
        isCustomise?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  jobTitle?: T;
  resume?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar".
 */
export interface Navbar {
  id: string;
  links: {
    name: string;
    href: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-logos".
 */
export interface HeroLogo {
  id: string;
  logos: {
    name: string;
    logo?: (string | null) | Media;
    size: number;
    /**
     * CSS left position (e.g. 10%, 120px)
     */
    left?: string | null;
    /**
     * CSS top position (e.g. 10%, 120px)
     */
    top?: string | null;
    zIndex?: number | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero".
 */
export interface HomeHero {
  id: string;
  headingLine1: string;
  /**
   * This line will be rendered with the blue gradient.
   */
  headingLine2: string;
  primaryButtonText: string;
  primaryButtonLink: string;
  secondaryButtonText: string;
  secondaryButtonLink: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats-bar".
 */
export interface StatsBar {
  id: string;
  stats: {
    value: string;
    label: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expertise".
 */
export interface Expertise {
  id: string;
  headingLine1: string;
  /**
   * This line will be rendered with the blue gradient.
   */
  headingLine2: string;
  cards: {
    title: string;
    description: string;
    product: string | Product;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-section".
 */
export interface AboutSection {
  id: string;
  visionHeading: string;
  visionDescription: string;
  missionHeading: string;
  missionDescription: string;
  visionImage?: (string | null) | Media;
  cultureHeading: string;
  cultureDescription: string;
  cultureButtonText: string;
  cultureButtonLink: string;
  cultureImage?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  description: string;
  socialLinks: {
    platform: 'linkedin' | 'instagram' | 'whatsapp' | 'email' | 'custom';
    url: string;
    id?: string | null;
  }[];
  columns: {
    title: string;
    links: {
      label: string;
      linkType: 'custom' | 'product' | 'job';
      url?: string | null;
      product?: (string | null) | Product;
      job?: (string | null) | Job;
      newTab?: boolean | null;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  copyright: string;
  bottomLinks: {
    label: string;
    linkType: 'custom' | 'product' | 'job';
    url?: string | null;
    product?: (string | null) | Product;
    job?: (string | null) | Job;
    newTab?: boolean | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: string;
  categories: {
    name: string;
    items: {
      name: string;
      logo?: (string | null) | Media;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-page".
 */
export interface AboutUsPage {
  id: string;
  heading: string;
  description: string;
  servicesSectionTitle: string;
  services: {
    title: string;
    desc: string;
    icon: 'layout-grid' | 'message-square' | 'bot' | 'phone-call' | 'workflow' | 'sparkles';
    id?: string | null;
  }[];
  whyChooseUsTitle: string;
  features: {
    title: string;
    icon: 'sparkles' | 'gauge' | 'circle-user' | 'headset' | 'shield-check';
    id?: string | null;
  }[];
  bottomStatement: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: string;
  heading: string;
  description: string;
  contactInfo: {
    label: string;
    value: string;
    href: string;
    icon: 'map-pin' | 'mail' | 'phone' | 'linkedin';
    id?: string | null;
  }[];
  formTitle: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page".
 */
export interface ProductsPage {
  id: string;
  badge: string;
  heading: string;
  description: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page".
 */
export interface CareersPage {
  id: string;
  badge: string;
  heading: string;
  description: string;
  perks: {
    name: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "culture-page".
 */
export interface CulturePage {
  id: string;
  badge: string;
  heading: string;
  description: string;
  bentoWideTitle: string;
  bentoWideDescription: string;
  bentoAccentTitle: string;
  values: {
    title: string;
    text: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar_select".
 */
export interface NavbarSelect<T extends boolean = true> {
  links?:
    | T
    | {
        name?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-logos_select".
 */
export interface HeroLogosSelect<T extends boolean = true> {
  logos?:
    | T
    | {
        name?: T;
        logo?: T;
        size?: T;
        left?: T;
        top?: T;
        zIndex?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero_select".
 */
export interface HomeHeroSelect<T extends boolean = true> {
  headingLine1?: T;
  headingLine2?: T;
  primaryButtonText?: T;
  primaryButtonLink?: T;
  secondaryButtonText?: T;
  secondaryButtonLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats-bar_select".
 */
export interface StatsBarSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expertise_select".
 */
export interface ExpertiseSelect<T extends boolean = true> {
  headingLine1?: T;
  headingLine2?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        product?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-section_select".
 */
export interface AboutSectionSelect<T extends boolean = true> {
  visionHeading?: T;
  visionDescription?: T;
  missionHeading?: T;
  missionDescription?: T;
  visionImage?: T;
  cultureHeading?: T;
  cultureDescription?: T;
  cultureButtonText?: T;
  cultureButtonLink?: T;
  cultureImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              linkType?: T;
              url?: T;
              product?: T;
              job?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  bottomLinks?:
    | T
    | {
        label?: T;
        linkType?: T;
        url?: T;
        product?: T;
        job?: T;
        newTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies_select".
 */
export interface TechnologiesSelect<T extends boolean = true> {
  categories?:
    | T
    | {
        name?: T;
        items?:
          | T
          | {
              name?: T;
              logo?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-page_select".
 */
export interface AboutUsPageSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  servicesSectionTitle?: T;
  services?:
    | T
    | {
        title?: T;
        desc?: T;
        icon?: T;
        id?: T;
      };
  whyChooseUsTitle?: T;
  features?:
    | T
    | {
        title?: T;
        icon?: T;
        id?: T;
      };
  bottomStatement?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  contactInfo?:
    | T
    | {
        label?: T;
        value?: T;
        href?: T;
        icon?: T;
        id?: T;
      };
  formTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page_select".
 */
export interface ProductsPageSelect<T extends boolean = true> {
  badge?: T;
  heading?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page_select".
 */
export interface CareersPageSelect<T extends boolean = true> {
  badge?: T;
  heading?: T;
  description?: T;
  perks?:
    | T
    | {
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "culture-page_select".
 */
export interface CulturePageSelect<T extends boolean = true> {
  badge?: T;
  heading?: T;
  description?: T;
  bentoWideTitle?: T;
  bentoWideDescription?: T;
  bentoAccentTitle?: T;
  values?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}